services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    env_file:
      - ./frontend/.env
    environment:
      VITE_PROXY_TARGET: http://backend:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
